# Generated by Django 3.2.7 on 2021-09-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Manager')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='acepted', max_length=50, verbose_name='status')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('content', models.TextField(verbose_name='')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.manager', verbose_name='manager')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('myTickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tickets', to='mainapp.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user', verbose_name='author'),
        ),
    ]
