# Generated by Django 3.2.7 on 2021-09-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='acepted', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='myTickets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tickets', to='mainapp.ticket', verbose_name='Mytickets'),
        ),
    ]
