# Generated by Django 3.2.7 on 2022-02-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20220202_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
